[package]
name = "tests"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
rustx.workspace = true
rustx-base.workspace = true

[[test]]
name = "base"
path = "base.rs"

[[test]]
name = "rustx"
path = "rustx.rs"

[lints]
workspace = true
