[package]
name = "bloats"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[features]
bloat-rustx = ["dep:rustx"]
bloat-base = ["dep:rustx-base"]

[dependencies]
rustx = { workspace = true, optional = true }
rustx-base = { workspace = true, optional = true }

[[bin]]
name = "bloat-rustx"
path = "rustx.rs"
required-features = ["bloat-rustx"]

[[bin]]
name = "bloat-base"
path = "base.rs"
required-features = ["bloat-base"]

[lints]
workspace = true
