name: CI

on:
  workflow_dispatch:

  push:
    branches: ['main']
    tags: ['v*']

  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  stable:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-stable, runner: '${{ matrix.os }}' }

  nightly:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    uses: ./.github/workflows/_base.yml
    with: { profile: nightly, command: ci-nightly, runner: '${{ matrix.os }}' }

  msrv:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    uses: ./.github/workflows/_base.yml
    with: { profile: msrv, command: ci-msrv, runner: '${{ matrix.os }}' }

  hack:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-hack, runner: '${{ matrix.os }}' }

  doc:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-doc }

  panic:
    uses: ./.github/workflows/_base.yml
    with: { profile: nightly, command: ci-panic }

  fmt:
    uses: ./.github/workflows/_base.yml
    with: { profile: nightly, command: ci-fmt }

  lint:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-lint }

  clippy:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-clippy }

  audit:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-audit }

  vet:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-vet }

  udeps:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-udeps }

  semver:
    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-semver }

  coverage:
    secrets: inherit
    needs: [stable, nightly, msrv, hack, doc, panic, fmt, lint, clippy, audit, vet, udeps, semver]

    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-coverage }

  publish:
    secrets: inherit
    needs: [coverage]
    if: github.event_name == 'push' && vars.PUBLISH_ENABLED == 'true'

    uses: ./.github/workflows/_base.yml
    with: { profile: stable, command: ci-publish }
